version: '3'
services:
    web:
        build: .
        command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db-postgres
        links:
            - "db-postgres:database"
        environment:
         NODE_ENV: production
         DB_HOST: database
         DB_PORT: 5433
         DB_USER: postgres
         DB_PASSWORD: postgres
         DB_NAME: scrapper
    db-postgres:
      container_name: db-postgres
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: scrapper
      ports:
        - '5432:5432'
      volumes: 
        - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
