FROM python:3.6-alpine
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip3 install -r requirements.txt
RUN pip3 install bs4 html5lib requests python-dateutil
COPY . /code/
RUN apk add postgresql-client

