# Generated by Django 2.2 on 2023-02-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=250)),
                ('loc', models.CharField(max_length=250)),
            ],
        ),
    ]
